Адаптировал footer под телефон
dl-academy-edu/mr-mishailov-roman-2 pull request #5
Opened 2020-09-08 18:42 UTC by AbellR3

Нужно переделать нижний блок в footer

2020-09-09 15:43 UTC, Mikchail requested changes

2020-09-09 15:43 UTC, Mikchail commented on src/components/footer/_footer.scss
> +    padding: 0 0;
тут достаточно вот так указать padding: 0;

2020-09-09 15:43 UTC, Mikchail commented on src/components/footer/_footer.scss
>      color: #AAAAAA;
а цвета не должны быть в переменных?

2020-09-09 16:22 UTC, AbellR3 commented on src/components/footer/_footer.scss
>      color: #AAAAAA;
должны быть

2020-09-13 13:18 UTC, Monkeybird2 approved these changes

2020-09-13 13:20 UTC, merged